org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# NeoForge Properties
minecraft_version=1.21.1
neo_version=21.1.125
neo_version_range=[21.1,)
loader_version_range=[4,)
mapping_channel=official
mapping_version=1.21.1

# Mod Properties
mod_version=1.0.0
maven_group=com.moulberry.flashback
archives_base_name=flashback_reforged

mod_id=flashback_reforged
mod_name=Flashback Reforged
mod_license=MIT
mod_authors=Tatuto
mod_description=Record your gameplay, view the recordings and export cinematic shots